#Funções data e hora

		#CURDATE() =  #CURRENT_DATE 
SELECT CURDATE() AS 'Data atual';
		#CURTIME() = #CURRENT_TIME()
SELECT CURTIME() AS 'Hora atual';
		#DATE_ADD(date, intervalo)
SELECT DATE_ADD(CURDATE(), INTERVAL 3 DAY) AS 'DATA DE VENCIMENTO';
		#DATE_SUB(date, intervalo)
SELECT DATE_SUB(CURDATE(), INTERVAL 3 YEAR) AS 'DATA DE MATRICULA';
		#DATEDIFF(expressão1, expressão2)
SELECT DATEDIFF(CURDATE(), DATE_SUB(CURDATE(), INTERVAL 10 DAY) ) AS 'DIAS DE ATRASO';
		#DATE_FORMAT(1, 2)
SELECT DATE_FORMAT(CURDATE(), '%D/%m/%Y') AS 'DATA FORMATADA';
#OBS = SE COLOCAR O Y = ANO, M = MES E D = DIA EM MAIUSCULO ELE PASSA MAIS OU MENOS INFORMAÇÃO.
		#DAYNAME()
SELECT DAYNAME(CURDATE()) AS 'DIA DA SEMANA(e)';
		#DAYOFMOTH()
SELECT DAYOFMONTH(CURDATE()) AS 'DIA DO MES(n)';
		#DAYOFWEEK
SELECT DAYOFWEEK(CURDATE()) AS 'DIA DA SEMANA(1,7)';
		#DAYOFYEAR
SELECT DAYOFYEAR(CURDATE()) AS 'DIA DO ANO(360)';
		#FROM_DAYS
SELECT FROM_DAYS(789033) AS 'DATA REAL';
		#NOW = #CURRENT_TIMESTAMP() - BASTANTE UTILIDADE PODENDO SÓ PEGAR HR OU SÓ DATA
SELECT NOW() AS 'DATA E HORA';
SELECT date_format(NOW(), '%d/%m/%Y - %h:%i:%s') AS 'DATA FORMATADA'; #obs = h = 12hrs, H = 24hrs
		#TIME(1)
SELECT TIME(CURRENT_TIMESTAMP()) AS 'HORA';
		#SEC_TO_TIME(1)
SELECT SEC_TO_TIME(1000) AS 'TEMPO REAL';
		#TIME_TO_SEC(1)
SELECT TIME_TO_SEC('00:32:44') AS 'Em segundos';
		#HOUR(1), MINUTE(1) OR SECOND(1)
SELECT HOUR(CURTIME()) AS hora,
	MINUTE(CURTIME()) AS minuto,
	SECOND(CURTIME()) AS segundos;
		#PERIOD_DIFF(1, 2)
SELECT PERIOD_DIFF( 202601, 202304) AS 'MESES RESTANTE';
		#TIMEDIFF(1, 2)
SELECT TIMEDIFF(CURTIME(), '09:20:45') AS 'DIFERENÇA';
		#QUARTER(DATE)
SELECT QUARTER(CURDATE()) AS 'TRIMESTRE DO ANO';
		#WEEK(DATE)
SELECT WEEK('2019-03-17') AS 'SEMANA DO ANO';
		#WEEKDAY(DATE)
SELECT WEEKDAY('2019-03-17') AS 'DIA  DA SEMANA';
		#YEAR(DATA)
SELECT YEAR('2019-03-17') AS 'ANO';
		#MONTH
SELECT MONTH('2019-03-17') AS 'MES';
		#DAY
SELECT DAY('2019-03-17') AS 'DIA';